### ISSUE TITLE
Add test case for function's second param.

### ISSUE THREAD

**Issue by naman03malhotra** [naman03malhotra/match-rules#27]
When a rule has a function value in the key, the value of that key from the source object is passed to the function as the first param and the whole source object as the second param.

**Comment by naman03malhotra** [comment]
Write a test case that also covers the example where the RULE contains the logic using the second param as well.

**Comment by StellaJung-Student** [comment]
@naman03malhotra , Just curious about the test case, in the test file,  there is already a test case for RULE_WITH_FUNCTION, which should be this case right? Only matchRules function are exported as default so I cannot write a test case except the function.
I am a student so can you explain more? or I am sorry to bother~.

**Comment by naman03malhotra** [comment]
@StellaJung-Student first of all, thank you for showing interest.

Let me explain:

If you have a function as a value for a key inside a RULE object, for example in `match_rules.spec.js` the
```
const RULE_WITH_FUNCTION = {
    user_profile: {
      age: (value) => value > 18 && value < 50,
    },
};
```
That function is called with the value as the first parameter and the source parameter as the second object.
`(value, sourceObject) => value > 18 && value < 50`

So we want the function to accommodate a use-case where the second param is also used. 

Now, let's say `mainSource` Object on line 38, has one more property `country: 'USA'`.

Now you might have a logic that depends on a data source from the original object. 

```
const SHOW_ADS_RULE_FOR_USA = {
    user_profile: {
      age: (value, sourceObject) => (value > 18 && value < 50) && ||` .....do something with sourceObject.country here`,
    },
};
```

So something like that, basically using the complete source object as a part of your complex logic for a `key`.

I hope it helps, let me know if you have more doubts regarding this, I'll be happy to explain.

**Comment by StellaJung-Student** [comment]
I understood the part~ but I didn't get how I can make a test for this.
And I tried to add test case but I don't think I get it.
I cannot test the function,recursiveRuleUtil, directly, correct?
This is what I did following your advice.
```
  const SHOW_ADS_RULE_FOR_COUNTRY = {
    user_profile: {
      age: (value, sourceObject) => (value > 18 && value < 50) && sourceObject.country === 'USA',
    },
  };
...
  const mainSource = {
    user_id: 123,
    user_profile: {
      age: 22,
      name: "Cool Name",
    },
    some_condition: true,
    some_feature: {
      can_edit: true,
      can_send: true,
      can_delete: false,
    },
    country: 'USA'
  };
...
  it("should execute the function with two parameters and second param when be includes source param's all keys", () => {
    expect(matchRules(mainSource, SHOW_ADS_RULE_FOR_COUNTRY)).toBe(true);
  });
```
Please give me more advice~
Thank you for your kindness.

**Comment by naman03malhotra** [comment]
@StellaJung-Student yeah that seems correct, can you please create a Pull request and send it for review.

And let's keep RULE name as `RULE_WITH_FUNCTION` only, as it documents the type of the rule.

**Comment by StellaJung-Student** [comment]
@naman03malhotra Thank you~
I used the same function name but I really don't  get the last part, but I just added it~
Please review and let me know if I am wrong~

**Comment by naman03malhotra** [comment]
@StellaJung-Student the last part says, show Ads if you meet these criteria (age, country) else you can also show Ads if you have an explicit flag which is true coming from backend.

**Comment by StellaJung-Student** [comment]
@naman03malhotra , I added spy like below
```
it("should execute the function with two parameters and second param when be includes source param's all keys", () => {
    const spyFn = jest.spyOn(RULE_WITH_FUNCTION.user_profile, "age")
    const result = matchRules(mainSource, RULE_WITH_FUNCTION);
    expect(spyFn).toBeCalledTimes(1)
    expect(spyFn).toBeCalledWith(mainSource.user_profile.age, mainSource)
    expect(result).toBe(true) 
  });
```
But, after that, I got the error below, which I never touch, any idea? I spent a lot of time but I didn't get it.
```
Test matchRules
    ✓ should throw error with proper message when either source or rules are missing (4 ms)
    ✓ should throw an error with proper message when an array is passed in the rules
    ✓ should return true when all the conditions of a rule is met and it should execute recursive function only when object has it own property (1 ms)
    ✓ should return false when at most one of the condition is not met
    ✓ should return true when all the conditions are met while passing multiple rules and it should execute recursive function only when object has it own property
    ✓ should return false when at most one of the condition is not met while passing multiple rules (1 ms)
    ✓ should return true when at least one RULE returns true while passing multiple rules compared with "or" operator
    ✓ should return false when all the RULEs returns false while passing multiple rules compared with "or" operator
    ✓ should return false when the value of the rule is missing in the source object (graceful exit)
    ✓ should return false when the value of the rule is undefined in the source object (graceful exit) (1 ms)
    ✓ should return false when the value of the rule is null in the source object (graceful exit)
    ✓ should return false when the value of the rule is Array in the source object (graceful exit)
    ✓ should return false when the value of the rule is String in the source object (graceful exit)
    ✓ should return false when the value of the rule is Number in the source object (graceful exit)
    ✓ should return true when the dynamic rule is matched to the source object (1 ms)
    ✓ should execute function when encountered in the rule and pass the corresponding key of that level from the source object
    ✓ should execute the function with two parameters and second param when be includes source param's all keys (1 ms)
    ✓ should do string matching when the rule has a string value
    ✕ should log the trace object when debug is true (4 ms)
    ✓ should log the trace object with no rule message when no key is passed in rule object and debug is true

  ● Test matchRules › should log the trace object when debug is true

    expect(received).toMatchSnapshot()

    Snapshot name: `Test matchRules should log the trace object when debug is true 1`

    - Snapshot  - 1
    + Received  + 1

    @@ -23,11 +23,11 @@
          },
          "2": Object {
            "user_profile": Object {
              "age": Object {
                "message": "Function was executed for the given rule with value: 22 (type: number)",
    -           "value": true,
    +           "value": undefined,
              },
            },
          },
        },
      ]

      211 | 
      212 |     expect(console.log).toBeCalled();
    > 213 |     expect(console.log.mock.calls[0]).toMatchSnapshot();
          |                                       ^
      214 |   });
      215 | 
      216 |   it("should log the trace object with no rule message when no key is passed in rule object and debug is true", () => {

      at Object.<anonymous> (tests/match_rules.spec.js:213:39)

 › 1 snapshot failed.
Snapshot Summary
 › 1 snapshot failed from 1 test suite. Inspect your code changes or run `npm test -- -u` to update them.

Test Suites: 1 failed, 1 total
Tests:       1 failed, 19 passed, 20 total
Snapshots:   1 failed, 1 passed, 2 total
Time:        0.869 s, estimated 219 s
```

**Comment by naman03malhotra** [comment]
@StellaJung-Student can you please push this code in the same branch, I'll debug this and get back to you.

**Comment by StellaJung-Student** [comment]
@naman03malhotra , I pushed it~. Thank you.

**Comment by naman03malhotra** [comment]
@StellaJung-Student basically you need to restore the spy after the spec is executed so that it doesn't affect the original function. Please check my latest commit on your branch.

**Comment by StellaJung-Student** [comment]
@naman03malhotra Thank you very much. It was very great time to learn how to use spy and mock function.

**Comment by naman03malhotra** [comment]
Yeah, thanks @StellaJung-Student  it was great working with you as well. Also, there are few ops related issues if you can check them out as well.
I'll merge this pull request with some other changes I wanted to push.

Do use this library to simplify the business logic in your next project.
Also, leave a [star](https://github.com/naman03malhotra/match-rules/stargazers) if you liked it.

**Comment by naman03malhotra** [comment]
I think, one comment is yet to be addressed https://github.com/naman03malhotra/match-rules/pull/33/files#r525933936

**Comment by naman03malhotra** [comment]
Fixed with PR: https://github.com/naman03malhotra/match-rules/pull/33
